"""PDF and Word adapters on development-only fixtures generated by tests/fixtures/make_formats.py (HB-04, read-only).

No model, no network, no database except the notes helpers (a temporary file). Nothing under data/ is written and nothing
under data/coral_pay/ is read.
"""

import base64
import io
import json
import sqlite3
import sys
import tempfile
import unittest
import zipfile
from pathlib import Path
from unittest import mock

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parent / "fixtures"))

import adapters
import ledger
import ledger_import
import make_formats as mf

NO_TEXT = "Page 2 has no readable text (scanned or image-only; OCR is not supported in this build)."


def paragraphs():
    return [text for kind, text in mf.hb04_blocks() if kind == "para"]


def headings():
    return [text for kind, text in mf.hb04_blocks() if kind == "heading"]


def flat(text):
    return " ".join(adapters.PAGE_MARKER.sub("", text).split())


class TestPdf(unittest.TestCase):
    def setUp(self):
        self.raw = mf.hb04_pdf(lines_per_page=12)
        self.out = adapters.adapt("HB-04.pdf", self.raw)
        self.text = self.out["canonical_text"]

    def test_every_hb04_sentence_is_in_the_text_in_order_with_a_marker_per_page(self):
        import pypdf
        pages = len(pypdf.PdfReader(io.BytesIO(self.raw)).pages)
        self.assertGreaterEqual(pages, 3)
        self.assertEqual(adapters.PAGE_MARKER.findall(self.text), [str(n) for n in range(1, pages + 1)])
        position = -1
        for sentence in headings() + paragraphs():
            self.assertTrue(adapters.quote_in_text(self.text, sentence), sentence)
        for sentence in paragraphs():
            at = flat(self.text).find(" ".join(sentence.split()))
            self.assertGreater(at, position)
            position = at
        self.assertEqual(self.out["problems"], [])
        self.assertEqual(self.out["format"], "PDF")

    def test_the_location_map_covers_each_page_and_names_the_adapter(self):
        pages = json.loads(self.out["location_map"])
        self.assertEqual([p["page"] for p in pages], list(range(1, len(pages) + 1)))
        for p in pages:
            self.assertTrue(self.text.startswith(f"[Page {p['page']}]", p["start"]))
        self.assertEqual(self.out["adapter_name"], "pdf-text")
        self.assertRegex(self.out["adapter_version"], r"^1 \(pypdf \d+\.\d+\.\d+\)$")

    def test_a_page_with_no_text_is_reported_and_the_other_pages_are_kept(self):
        out = adapters.adapt("scan.pdf", mf.partial_scan_pdf())
        self.assertEqual(out["problems"], [NO_TEXT])
        self.assertEqual([p["page"] for p in json.loads(out["location_map"])], [1, 3])
        self.assertNotIn("[Page 2]", out["canonical_text"])
        self.assertIn("[Page 3]", out["canonical_text"])

    def test_an_image_only_pdf_is_refused_with_the_plain_message(self):
        for pages in (1, 3):
            with self.assertRaises(adapters.AdapterError) as caught:
                adapters.adapt("scan.pdf", mf.image_only_pdf(pages))
            self.assertEqual(str(caught.exception),
                             "No page in this PDF has readable text (scanned or image-only; OCR is not supported in this build).")

    def test_damaged_wrong_and_password_protected_pdfs_are_refused(self):
        with self.assertRaisesRegex(adapters.AdapterError, "not a PDF"):
            adapters.adapt("a.pdf", b"just some text, not a pdf")
        with self.assertRaisesRegex(adapters.AdapterError, "could not be read"):
            adapters.adapt("a.pdf", b"%PDF-1.4\n1 0 obj << /Broken\n%%EOF")
        import pypdf
        locked = None
        for algorithm in ("RC4-128", "RC4-40", "AES-128"):  # pypdf writes RC4 without extra libraries
            try:
                writer = pypdf.PdfWriter(clone_from=io.BytesIO(self.raw))
                writer.encrypt("secret", algorithm=algorithm)
                out = io.BytesIO()
                writer.write(out)
                locked = out.getvalue()
                break
            except Exception:
                continue
        if locked is None:
            self.skipTest("this pypdf install cannot write an encrypted test file")
        self.assertTrue(pypdf.PdfReader(io.BytesIO(locked)).is_encrypted)
        with self.assertRaisesRegex(adapters.AdapterError, "password-protected"):
            adapters.adapt("locked.pdf", locked)

    def test_too_many_pages_and_too_much_text_are_refused(self):
        with mock.patch.object(adapters, "MAX_PDF_PAGES", 2):
            with self.assertRaisesRegex(adapters.AdapterError, "up to 2\\."):
                adapters.adapt("a.pdf", self.raw)
        with mock.patch.object(adapters, "MAX_CANONICAL_CHARS", 100):
            with self.assertRaisesRegex(adapters.AdapterError, "too much text"):
                adapters.adapt("a.pdf", self.raw)

    def test_the_same_bytes_give_the_same_text(self):
        again = adapters.adapt("HB-04.pdf", self.raw)
        self.assertEqual(ledger_import.sha256_hex(again["canonical_text"]), ledger_import.sha256_hex(self.text))


class TestDocx(unittest.TestCase):
    def test_every_hb04_sentence_and_heading_is_in_the_text_in_order(self):
        out = adapters.adapt("HB-04.docx", mf.hb04_docx())
        text = out["canonical_text"]
        position = -1
        for sentence in headings() + paragraphs():
            self.assertTrue(adapters.quote_in_text(text, sentence), sentence)
        for sentence in paragraphs():
            at = flat(text).find(" ".join(sentence.split()))
            self.assertGreater(at, position)
            position = at
        self.assertEqual((out["format"], out["problems"], out["adapter_name"]), ("Word", [], "docx"))
        self.assertRegex(out["adapter_version"], r"^1 \(python-docx \d+\.\d+\.\d+\)$")

    def test_tables_are_flattened_headers_and_footers_ignored_and_images_counted(self):
        out = adapters.adapt("x.docx", mf.hb04_docx(with_extras=True))
        text = out["canonical_text"]
        self.assertIn("Capability | Scope | Approval\nPayout ledger connector | Singapore | No named exception approved", text)
        self.assertNotIn("CONFIDENTIAL HEADER TEXT", text)
        self.assertNotIn("FOOTER PAGE TEXT", text)
        self.assertEqual(out["problems"], ["1 image was not read (pictures are not supported in this build)."])

    def test_tracked_changes_read_as_accepted_and_are_reported(self):
        out = adapters.adapt("x.docx", mf.docx_with_tracked_changes())
        self.assertEqual(out["canonical_text"], "The connector will handle 12,000 payouts per day.")
        self.assertEqual(out["problems"], ["The document has 2 tracked changes; the text read is the version with every change accepted."])

    def test_wrong_old_empty_and_oversized_word_files_are_refused(self):
        ole = adapters.OLE_MAGIC + b"\x00" * 600
        with self.assertRaisesRegex(adapters.AdapterError, r"\.doc\) are not supported"):
            adapters.adapt("old.doc", ole)
        with self.assertRaisesRegex(adapters.AdapterError, "older or password-protected"):
            adapters.adapt("x.docx", ole)
        with self.assertRaisesRegex(adapters.AdapterError, "not a Word"):
            adapters.adapt("x.docx", b"plain text")
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w") as zf:
            zf.writestr("hello.txt", "x")
        with self.assertRaisesRegex(adapters.AdapterError, "not a Word"):
            adapters.adapt("x.docx", buf.getvalue())
        import docx
        empty = io.BytesIO()
        docx.Document().save(empty)
        with self.assertRaisesRegex(adapters.AdapterError, "no text to read"):
            adapters.adapt("x.docx", empty.getvalue())

    def test_a_zip_bomb_is_refused_before_anything_is_unpacked(self):
        bomb = io.BytesIO()
        with zipfile.ZipFile(bomb, "w", zipfile.ZIP_DEFLATED) as zf:
            zf.writestr("word/document.xml", b"\x00" * (adapters.MAX_DOCX_UNPACKED + 1024))
        self.assertLess(len(bomb.getvalue()), adapters.MAX_UPLOAD_BYTES)
        with self.assertRaisesRegex(adapters.AdapterError, "too large once unpacked"):
            adapters.adapt("x.docx", bomb.getvalue())


class TestDispatch(unittest.TestCase):
    def test_markdown_and_text_are_exactly_what_they_were(self):
        raw = mf.hb04_markdown().encode("utf-8")
        expected = ledger_import.markdown_adapter(raw)
        for name, label in (("HB-04_proposal.md", "Markdown"), ("notes.txt", "Text")):
            out = adapters.adapt(name, raw)
            for key in ("canonical_text", "location_map", "adapter_name", "adapter_version"):
                self.assertEqual(out[key], expected[key])
            self.assertEqual((out["format"], out["problems"]), (label, []))
            self.assertEqual(ledger_import.sha256_hex(out["canonical_text"]), ledger_import.sha256_hex(expected["canonical_text"]))

    def test_each_format_records_its_own_adapter(self):
        names = {adapters.adapt("a.pdf", mf.hb04_pdf())["adapter_name"], adapters.adapt("a.docx", mf.hb04_docx())["adapter_name"],
                 adapters.adapt("a.md", b"# x\n\ny\n")["adapter_name"]}
        self.assertEqual(len(names), 3)

    def test_types_sizes_and_encodings_that_are_not_supported_are_refused_plainly(self):
        for name in ("a.exe", "a.zip", "a.docm", "noextension", "a.xlsx", ".pdf.exe"):
            with self.assertRaisesRegex(adapters.AdapterError, "PDF, Word \\(.docx\\), Markdown and text"):
                adapters.adapt(name, b"x")
        with self.assertRaisesRegex(adapters.AdapterError, "empty"):
            adapters.adapt("a.pdf", b"")
        with self.assertRaises(adapters.AdapterError) as big:
            adapters.adapt("a.pdf", b"%PDF-" + b"0" * adapters.MAX_UPLOAD_BYTES)
        self.assertEqual((str(big.exception), big.exception.status), ("The file is larger than 10 MB.", 413))
        with self.assertRaisesRegex(adapters.AdapterError, "not UTF-8"):
            adapters.adapt("a.md", b"\xff\xfe\x00bad")
        with self.assertRaisesRegex(adapters.AdapterError, "empty"):
            adapters.adapt("a.md", b"  \n\n ")
        self.assertEqual(adapters.extension("C:\\docs\\Proposal.PDF"), ".pdf")
        self.assertEqual(adapters.format_label("pdf-text"), "PDF")
        self.assertEqual(adapters.format_label("whatever", "x.txt"), "Text")


class TestQuotesTraceBack(unittest.TestCase):
    def pdf(self, pages):
        return adapters.adapt("a.pdf", mf.text_pdf(pages))

    def test_a_quote_resolves_to_its_page(self):
        out = self.pdf([["Alpha one is on the first page."], ["Beta two is on the second page."], ["Gamma three."]])
        for quote, page in (("Alpha one is on the first page.", 1), ("Beta two is on the second page.", 2), ("Gamma three.", 3)):
            self.assertEqual(adapters.locate_page(out["canonical_text"], out["location_map"], quote), page)
        self.assertEqual(adapters.locate_page(out["canonical_text"], out["location_map"], "  Beta two  is on\nthe second page. "), 2)

    def test_a_quote_that_crosses_a_page_break_is_found_and_belongs_to_the_page_it_starts_on(self):
        lines = mf.wrap("The payout ledger connector will handle up to 12,000 payouts per day at launch and later more.", 40)
        self.assertGreaterEqual(len(lines), 3)
        out = self.pdf([lines[:2], lines[2:]])
        quote = " ".join(lines)
        self.assertIn("[Page 2]", out["canonical_text"])
        self.assertTrue(adapters.quote_in_text(out["canonical_text"], quote))
        self.assertEqual(adapters.locate_page(out["canonical_text"], out["location_map"], quote), 1)

    def test_an_absent_or_ambiguous_quote_has_no_page(self):
        out = self.pdf([["Same sentence here."], ["Same sentence here."], ["Only once."]])
        self.assertIsNone(adapters.locate_page(out["canonical_text"], out["location_map"], "Same sentence here."))
        self.assertIsNone(adapters.locate_page(out["canonical_text"], out["location_map"], "Never written."))
        self.assertFalse(adapters.quote_in_text(out["canonical_text"], "Never written."))
        self.assertIsNone(adapters.locate_page("plain markdown", json.dumps([{"paragraph": 1, "start": 0, "end": 5}]), "plain"))


class TestNotesTable(unittest.TestCase):
    def setUp(self):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        self.conn = ledger.open_ledger(Path(tmp.name) / "ledger.sqlite")
        self.addCleanup(self.conn.close)

    def version(self):
        deal = self.conn.execute("INSERT INTO deals (slug, kind, display_name) VALUES ('u_0123456789abcdef', 'user', 'X')").lastrowid
        source = self.conn.execute("INSERT INTO sources (deal_id, source_key, display_name) VALUES (?, 'D-01', 'x')", (deal,)).lastrowid
        return self.conn.execute(
            "INSERT INTO source_versions (source_id, version_no, original_sha256, canonical_sha256, adapter_name, adapter_version,"
            " doc_type, doc_date, original_filename, canonical_text, location_map) VALUES (?, 1, ?, ?, 'pdf-text', '1', 'proposal',"
            " '2026-11-01', 'a.pdf', 't', '[]')", (source, "0" * 64, "1" * 64)).lastrowid

    def test_notes_are_additive_idempotent_immutable_and_ordered(self):
        vid = self.version()
        self.assertEqual(adapters.notes_for(self.conn, [vid]), {})  # no table yet: nothing, and no error
        adapters.ensure_notes_schema(self.conn)
        adapters.ensure_notes_schema(self.conn)
        adapters.save_notes(self.conn, vid, ["first", "second"])
        self.conn.commit()
        self.assertEqual(adapters.notes_for(self.conn, [vid]), {vid: ["first", "second"]})
        with self.assertRaises(sqlite3.IntegrityError):
            self.conn.execute("UPDATE source_version_notes SET message = 'x'")
        with self.assertRaises(sqlite3.IntegrityError):
            self.conn.execute("DELETE FROM source_version_notes")
        self.assertEqual(self.conn.execute("SELECT value FROM schema_meta WHERE key = 'schema_version'").fetchone()[0], "1")
        self.assertEqual(adapters.notes_for(self.conn, []), {})


if __name__ == "__main__":
    unittest.main()
